name: school_management_mobile_frontend_students
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.1.0
  cloud_firestore: ^6.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.0
  get_it: ^9.2.0
  go_router: ^17.0.0
  http: ^1.6.0
  internet_connection_checker: ^3.0.1
  loading_animation_widget: ^1.3.0
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.4
  intl: 0.20.2
  curved_navigation_bar: ^1.0.6
  dio: ^5.9.2
  flutter_secure_storage: ^10.3.1
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^22.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2
  share_plus: ^12.0.2
  gal: ^2.3.2
  pdf: ^3.12.0
  printing: ^5.14.3
  confetti: ^0.8.0
  firebase_ai: ^3.14.1
  firebase_app_check: ^0.4.5+2
  timezone: ^0.11.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "@color/ic_launcher_bg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package